### PR TITLE
Lots of little changes

### PR DESCRIPTION
**Pull request by robbiet480**
- Fix misspelling of categories (previously it was catagories)
- Add Redis caching support to cache results from the API for performance gains
- Enable HTTPS
- Update to version 3 of the API
- Remove unnecessary callbacks
- package.json has been expanded and is now valid

Thanks also goes to @ashking for the original version 3 + categories URL fixes!

### CODE REVIEW

**Comment by RichardCzechowski** [comment]
So glad you guys got to this! I have been intending on going back and adding API3 support for weeks. Bravo! I won't have time to review this and update npm until next week. If nobody else @Coding-House does in the meantime, please ping me.

**Comment by robbiet480** [comment]
@Coding-House Might also be a good idea to rename this package to just `crunchbase`, as API V2 has been shut down for quite some time...

**Comment by RichardCzechowski** [comment]
That was something else I had thought to suggest. It may actually better for you to make your fork the official repo for CrunchbaseV3, since I think I am the only one who regularly pays attention to this one.

**Comment by robbiet480** [comment]
@RichardCzechowski Okay, that's fine. Will do that momentarily.

**Comment by robbiet480** [comment]
@RichardCzechowski Done! About to publish to npm. I added you as a contributor to the Github repo. Going to close this PR now. 

New fork can be found [here](https://github.com/robbiet480/node-crunchbase-api)

**Comment by RichardCzechowski** [comment]
@robbiet480 thanks! I really appreciate it.

**Comment by ashking** [comment]
@robbiet480 Thanks for the updates! Much appreciated :+1:

**Pull request closed without merging**
